name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.SKD_DOCKER_BUILD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: paulyk/skd-server:latest
        platforms: linux/amd64,linux/arm64